fix restore script properly

diff --git a/templates/default/openvpnas-restore.erb b/templates/default/openvpnas-restore.erb
--- a/templates/default/openvpnas-restore.erb
+++ b/templates/default/openvpnas-restore.erb
@@ -2,7 +2,7 @@
 
 # Generated by Chef
 
-# ./usr/local/openvpn_as/scripts/sqlite3 <[TEXT_FILE] [DB_FILE]
+# ./usr/local/openvpn_as/scripts/sqlite3 [DB_FILE] < [TEXT_FILE]
 
 # /usr/local/openvpn_as/etc
 # certs.db
@@ -15,6 +15,22 @@ RESTORE_BUCKET=<%= node['openvpnas']['backup']['bucket'] %>
 RESTORE_DIR=/tmp/openvpnas_restore
 
 echo 'starting restore'
+echo
+
+echo 'this will remove current config'
+read -r -p "Are you sure? [y/N] " response
+case $response in
+    [yY][eE][sS]|[yY])
+    ;;
+  *)
+    exit 0
+    ;;
+esac
+
+if [ -f $OPENVPNAS_DIR/RESTORED ]; then
+  echo 'existing restore found, aborting!'
+  exit 1
+fi
 
 # make a temporary restore directory
 mkdir -p $RESTORE_DIR
@@ -22,7 +38,7 @@ cd $RESTORE_DIR
 
 # download the latest backup
 RESTORE_NAME=$(/usr/local/bin/aws s3 ls s3://$RESTORE_BUCKET | grep -o 'openvpnas-backup[^\n]*' | tail -1)
-aws s3 cp s3://$RESTORE_BUCKET/$RESTORE_NAME.tar.gz openvpnas-backup.tar.gz
+/usr/local/bin/aws s3 cp s3://$RESTORE_BUCKET/$RESTORE_NAME openvpnas-backup.tar.gz
 
 # extract the backup to the temp dir
 
@@ -31,11 +47,13 @@ tar zxf openvpnas-backup.tar.gz .
 # stop openvpnas
 /etc/init.d/openvpnas stop
 
+rm -f $OPENVPNAS_DIR/etc/db/*.db
+
 # iterate the database files
-for DBNAME in *.db
+for DBNAME in *.db.dump
 do
   echo "restoring $DBNAME"
-  $OPENVPNAS_DIR/scripts/sqlite3 $OPENVPNAS_DIR/etc/db/$DBNAME < $DBNAME.dump
+  $OPENVPNAS_DIR/scripts/sqlite3 $OPENVPNAS_DIR/etc/db/${DBNAME%.dump} < $DBNAME
 done
 
 # start openvpnas
